name: Deploy Landing Page to Strato

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Deploy via rsync
        run: |
          sudo apt-get install -y sshpass
          sshpass -p "${{ secrets.SSH_PASSWORD }}" \
          rsync -rlgoDzvc --delete --mkpath \
            -e "ssh -p ${{ secrets.SSH_PORT || 22 }} -o StrictHostKeyChecking=no -o UpdateHostKeys=no" \
            --exclude='.git*' \
            --exclude='.github' \
            ./ \
            ${{ secrets.SSH_USERNAME }}@${{ secrets.SSH_HOST }}:${{ secrets.SSH_TARGET_LANDING }}
